//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMe.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individual
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> BobYear { get; set; }
        public string BobMonth { get; set; }
        public Nullable<int> BdDDay { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> FieldOfBusiness { get; set; }
        public Nullable<int> GraduationCountry { get; set; }
        public Nullable<int> GraduationUniversity { get; set; }
        public Nullable<int> YearsOfExperience { get; set; }
        public Nullable<int> TypeOfEmployment { get; set; }
        public string CvAttachment { get; set; }
        public Nullable<int> AcademicDegree { get; set; }
        public string ImageUrl { get; set; }
        public string EmploymentHistory { get; set; }
        public Nullable<int> MinimumSalary { get; set; }
        public Nullable<int> RelationshipStatus { get; set; }
        public Nullable<int> AbilityToTravel { get; set; }
        public string CoverLetter { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
