//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMe.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobInfo
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int JobTypeId { get; set; }
        public int ExperienceLevelId { get; set; }
        public int SkilesId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string JobDescription { get; set; }
        public string Responsibilities { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
