//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMe.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestedCv
    {
        public int Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid IndividualId { get; set; }
        public bool IsUnlocked { get; set; }
    }
}
