//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMe.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkill
    {
        public int Id { get; set; }
        public int SkillId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Lookup Lookup { get; set; }
    }
}
